name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true
        continue-on-error: true # Allow the job to continue to the next step even if this one fails

      - name: Print test logs
        if: failure()
        run: |
          echo "Tests failed, printing logs..."
          docker logs <container_id> # Replace <container_id> with the correct ID or name if necessary

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          target: prod
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
        if: success() # Only run this step if the previous steps were successful

      - name: Post build cleanup
        run: docker system prune -f
